"""
Multi-Touch Attribution (MTA) Engine
Implements:
1. First-Touch Attribution: 100% credit to the initial discovery touchpoint.
2. Last-Touch Attribution: 100% credit to the closing touchpoint before conversion.
3. Linear Attribution: Equal credit distributed across all journey touches.
4. Time-Decay Attribution: Exponentially decays weight with half-life (e.g. 7 days).
5. Markov Chain Attribution: Removal effect heuristic quantifying channel contribution.
"""
import pandas as pd
import numpy as np

class MultiTouchAttribution:
    def __init__(self, half_life_days: float = 7.0):
        self.half_life_days = half_life_days

    def run_rule_based_attribution(self, df_touchpoints: pd.DataFrame) -> pd.DataFrame:
        """
        Calculates attribution weights for First, Last, Linear, and Time-Decay.
        Returns a DataFrame summarizing attributed conversions and revenue by channel.
        """
        tp = df_touchpoints.copy()
        tp["event_timestamp"] = pd.to_datetime(tp["event_timestamp"])

        # Filter to touchpoints associated with conversions or customer journeys that converted
        converting_users = set(tp[tp["conversion_flag"] == 1]["unified_customer_id"].unique())
        tp_conv = tp[tp["unified_customer_id"].isin(converting_users)].sort_values(
            ["unified_customer_id", "event_timestamp"]
        )

        results = []
        for ucid, group in tp_conv.groupby("unified_customer_id"):
            conv_events = group[group["conversion_flag"] == 1]
            if len(conv_events) == 0:
                continue

            # Total revenue generated by this user
            total_rev = conv_events["attributed_revenue"].sum()
            n_touches = len(group)
            
            # Times
            last_time = group["event_timestamp"].max()

            for idx, (_, row) in enumerate(group.iterrows()):
                ch = row["channel"]
                camp = row["campaign_name"]
                t_time = row["event_timestamp"]

                # First touch
                ft_weight = 1.0 if idx == 0 else 0.0
                # Last touch
                lt_weight = 1.0 if idx == (n_touches - 1) else 0.0
                # Linear
                lin_weight = 1.0 / n_touches
                # Time decay
                days_diff = (last_time - t_time).total_seconds() / (24 * 3600)
                decay_weight = 2 ** (-days_diff / self.half_life_days)

                results.append({
                    "unified_customer_id": ucid,
                    "channel": ch,
                    "campaign_name": camp,
                    "revenue": total_rev,
                    "ft_conv": ft_weight,
                    "ft_rev": ft_weight * total_rev,
                    "lt_conv": lt_weight,
                    "lt_rev": lt_weight * total_rev,
                    "lin_conv": lin_weight,
                    "lin_rev": lin_weight * total_rev,
                    "decay_raw_weight": decay_weight,
                    "total_rev": total_rev
                })

        df_res = pd.DataFrame(results)
        
        # Normalize time decay per user
        user_decay_sum = df_res.groupby("unified_customer_id")["decay_raw_weight"].transform("sum")
        df_res["td_conv"] = df_res["decay_raw_weight"] / user_decay_sum
        df_res["td_rev"] = df_res["td_conv"] * df_res["total_rev"]

        # Channel level roll-up
        channel_summary = df_res.groupby("channel").agg(
            first_touch_conversions=("ft_conv", "sum"),
            first_touch_revenue=("ft_rev", "sum"),
            last_touch_conversions=("lt_conv", "sum"),
            last_touch_revenue=("lt_rev", "sum"),
            linear_conversions=("lin_conv", "sum"),
            linear_revenue=("lin_rev", "sum"),
            time_decay_conversions=("td_conv", "sum"),
            time_decay_revenue=("td_rev", "sum")
        ).round(2).reset_index()

        return channel_summary

    def run_markov_attribution(self, df_touchpoints: pd.DataFrame) -> pd.DataFrame:
        """
        Markov Chain removal effect modeling.
        Tracks state transitions: Start -> Channel_i -> Channel_j -> [Conversion / Null].
        """
        tp = df_touchpoints.copy().sort_values(["unified_customer_id", "event_timestamp"])
        
        # Construct path per customer
        paths = []
        for ucid, group in tp.groupby("unified_customer_id"):
            channels = list(group["channel"].values)
            has_converted = (group["conversion_flag"] == 1).any()
            outcome = "Conversion" if has_converted else "Null"
            path = ["Start"] + channels + [outcome]
            paths.append(path)

        # Transition matrix
        transitions = {}
        for p in paths:
            for i in range(len(p) - 1):
                cur_state, next_state = p[i], p[i+1]
                if cur_state not in transitions:
                    transitions[cur_state] = {}
                transitions[cur_state][next_state] = transitions[cur_state].get(next_state, 0) + 1

        # Normalize probabilities
        prob_matrix = {}
        for state, nxt in transitions.items():
            tot = sum(nxt.values())
            prob_matrix[state] = {k: v / tot for k, v in nxt.items()}

        unique_channels = set(tp["channel"].unique())
        
        # Base conversion rate from Start via simple path simulation / removal heuristic
        def get_prob_to_conversion(matrix, removed_channel=None):
            # Breadth-first / simplified reachability probability to Conversion
            # For tree-like or short marketing paths, calculate cumulative probability
            states = {"Start": 1.0}
            conv_prob = 0.0
            
            for _ in range(6): # max 6 hops
                new_states = {}
                for s, prob in states.items():
                    if s == "Conversion":
                        conv_prob += prob
                        continue
                    if s in ["Null", removed_channel]:
                        continue
                    if s in matrix:
                        for nxt_s, t_prob in matrix[s].items():
                            new_states[nxt_s] = new_states.get(nxt_s, 0.0) + (prob * t_prob)
                states = new_states
            return conv_prob

        base_conv = get_prob_to_conversion(prob_matrix)
        
        removal_effects = {}
        for ch in unique_channels:
            p_without = get_prob_to_conversion(prob_matrix, removed_channel=ch)
            removal_effects[ch] = max(0.0, (base_conv - p_without) / base_conv) if base_conv > 0 else 0.0

        # Normalize removal effects
        total_effect = sum(removal_effects.values())
        markov_shares = {k: (v / total_effect if total_effect > 0 else 1.0/len(unique_channels)) for k, v in removal_effects.items()}

        df_markov = pd.DataFrame([
            {"channel": ch, "markov_weight": round(weight, 4), "markov_share_pct": round(weight * 100, 2)}
            for ch, weight in sorted(markov_shares.items(), key=lambda x: x[1], reverse=True)
        ])
        return df_markov

if __name__ == "__main__":
    from src.cdp.database import CDPDatabase
    db = CDPDatabase()
    df_tp = db.query("SELECT * FROM campaign_touchpoint;")
    mta = MultiTouchAttribution()
    rule_res = mta.run_rule_based_attribution(df_tp)
    markov_res = mta.run_markov_attribution(df_tp)
    print("MTA Rule-Based Summary:")
    print(rule_res)
    print("\nMarkov Attribution:")
    print(markov_res)
